routes/web.php
Route::resource('uploadwatchimage','WatchImageController');
Route::get('uploadwatchimage/createImage/{id}','WatchImageController@createImage');
Route::resource('watchcontactus', 'WatchContactusController');
Route::resource('watchblog', 'WatchBlogController');
Route::post('watchblog/update/{id}','WatchBlogController@update');
Route::get('watchBlogDeleteImage/{id}','WatchBlogImageController@destroy');
Route::resource('uploadwatchblogimage','WatchBlogImageController');
Route::get('uploadwatchblogimage/createImage/{id}','WatchBlogImageController@createImage');

// ---------------------- WATCH LISTING DATA MENU ENDS HERE --------------//


Route::get('watch/contract', 'admin\WatchContractController@createContract');
Route::post('watch/contract/update', ['as' => 'watchContract.update', 'uses' => 'admin\WatchContractController@updateContract']);
//Route::get('watch/popup', 'WatchContractController@createContract');



//---------------------- PROFILE STARTS----------------------------//

Route::resource('profile', 'ProfileController');
Route::get('profile/{id}', 'ProfileController@show');

//---------------------- PROFILE ENDS----------------------------//

//---------------------- AGENT STARTS----------------------------//

Route::resource('agencies', 'AgenciesController');
Route::post('agenciesData/update/{id}','AgenciesController@update');
Route::get('agenciesDeleteImage/{id}','AgenciesImageController@destroy');
Route::resource('uploadagenciesimage','AgenciesImageController');
Route::get('uploadagenciesimage/createImage/{id}','AgenciesImageController@createImage');
Route::resource('agentdata', 'AgentController');
Route::post('agentData/update/{id}','AgentController@update');
Route::resource('uploadagentimage','AgentImageController');
Route::get('agentDeleteImage/{id}','AgentImageController@destroy');
Route::get('uploadagentimage/createImage/{id}','AgentImageController@createImage');
Route::resource('agentjobposition','AgentJobPositionController');
//---------------------- AGENT ENDS----------------------------//

//---------------------- CONTRACTED PRODUCTS STARTS----------------------------//
Route::resource('contactus', 'ContactusController');
Route::resource('propertycontractedproduct', 'PropertyContractedDetailsController');
Route::resource('watchcontractedproduct', 'WatchContractedDetailsController');
Route::resource('automobilecontractedproduct', 'AutomobileContractedDetailsController');

//---------------------- CONTRACTED PRODUCTS STARTS----------------------------//

//---------------------- Automobile Transmission STARTS----------------------------//
Route::resource('transmission','TransmissionController');
//---------------------- Automobile Transmission Ends----------------------------//

//---------------------- Language STARTS----------------------------//
Route::resource('language','LanguageController');
//---------------------- Language Ends------------------------------//

//---------------------- Testimonial STARTS----------------------------//
Route::resource('testimonial','admin\TestimonialController');
//---------------------- Testimonial Ends------------------------------//

//---------------------- CMS Pages STARTS----------------------------//
Route::resource('cmspages','CmsPagesController');
//---------------------- CMS Pages Ends------------------------------//

//---------------------- FAQ Management STARTS----------------------------//
Route::resource('faq-cat','FaqCategoryController');
Route::resource('faq-subcat','FaqSubCategoryController');
Route::resource('faq','FaqController');
//Sub category ajax request
Route::post('faqsub-cat','FaqSubCategoryController@getSubCategory');
//---------------------- FAQ Management Ends------------------------------//
});

});	
//Dealer Login 
Route::group(['prefix'=> 'dealer/'], function (){
	Route::get('/logout', function(){
   Auth::logout();
   return Redirect::to('dealer/login');
});
	Route::get('/login', 'DealerLoginController@login')->name('dealer.login');
	Route::get('/reset', 'DealerPasswordResetController@index');
	Route::post('/logincheck', 'DealerLoginController@checklogin')->name('logincheck');
	Route::get('/register', 'DealerLoginController@register')->name('dealer.register');
	Route::post('/newDealerRegister', 'DealerLoginController@newDealerRegister')->name('newDealerRegister');
});
Route::group(['middleware'=>['auth','dealer']], function (){

	Route::group(['prefix'=> 'dealer/'], function (){
		   Route::get('/dashboard', 'DealerPortalController@index');
		    Route::post('/getCity', 'DealerPortalController@getCityByState');
            Route::get('/addUser', 'DealerAddUserFrontEndController@create');
            Route::get('/editUser/{agentId}', 'DealerAddUserFrontEndController@edit');
            Route::get('/listagents', 'DealerAddUserFrontEndController@listAgents');
            Route::post('/addUserData', 'DealerAddUserFrontEndController@store');
            Route::post('/updateUserData', 'DealerAddUserFrontEndController@update');
            Route::get('/inventoryList', 'DealerInventoryController@inventoryList')->name('inventoryList');
            Route::get('/prospect', 'DealerEnquiryController@prospectList')->name('prospectList');
            Route::get('/enquiryList', 'DealerEnquiryController@enquiryList')->name('enquiryList');
            Route::resource('dealerManagement', 'DealerManagementController');
            Route::get('/addAuto', 'DealerAddListingsController@createAuto');
            Route::get('/addWatch', 'DealerAddListingsController@createWatch');
            Route::get('/addProperty', 'DealerAddListingsController@createProperty');
            Route::post('/addWatchData', 'DealerAddListingsController@storeWatchData');
            Route::post('/addAutoData', 'DealerAddListingsController@storeAutoData');
            Route::post('/addPropertyData', 'DealerAddListingsController@addPropertyData');
            Route::post('/getState', 'DealerAddListingsController@getStateByCountry');
            Route::post('/getCity', 'DealerAddListingsController@getCityByState');
            Route::post('/top_property_type/getSubType', 'DealerAddListingsController@getSubPropertyType');
            
            Route::get('editwatchads/{id}', 'ManageDealerInventoryController@editWatch');
            Route::get('deletewatchadsimage/{id}/{imagetype}', 'ManageDealerInventoryController@deleteWatch');
            Route::post('storewatch', 'ManageDealerInventoryController@storeWatch');
            Route::get('editautoads/{id}', 'ManageDealerInventoryController@editAuto');
            Route::get('deleteautoadsimage/{id}/{imagetype}', 'ManageDealerInventoryController@deleteAuto');
            Route::post('storeauto', 'ManageDealerInventoryController@storeAuto');
            Route::get('editpropertyads/{id}', 'ManageDealerInventoryController@editProperty');
            Route::get('deletepropertyadsimage/{id}/{imagetype}', 'ManageDealerInventoryController@deleteProperty');
            Route::post('storeproperty', 'ManageDealerInventoryController@storeProperty');
	});
});

//User Login
Route::group(['prefix'=> 'user/'], function (){
	Route::get('/logout', function(){
   Auth::logout();
   session(['url.intended' => url()->previous()]);
	    return redirect(session()->get('url.intended'));
});
    Route::get('/checkUser', 'UserLoginController@checkRegisteredUser')->name('checkUser');
	Route::get('/login', 'UserLoginController@login')->name('user.login');
	Route::post('/logincheck', 'UserLoginController@checklogin')->name('logincheck');
	Route::get('/register', 'UserLoginController@register')->name('user.register');
	Route::post('/newUserRegister', 'UserLoginController@newUserRegister')->name('newUserRegister');
});
Route::group(['middleware'=>['auth','user']], function (){

	Route::group(['prefix'=> 'user/'], function (){
	    Route::post('/savelisting','SaveListingController@saveListing');
		  Route::get('/dashboard', function () {
		    return view('user.dashboard.dashboard');
		    });
	});
});
//

//privateSeller Login
Route::group(['prefix'=> 'privateSeller/'], function (){
	Route::get('/logout', function(){
   Auth::logout();
   return Redirect::to('privateSeller/login');
});
	Route::get('/login', 'PrivateSellerLoginController@login')->name('privateSeller.login');
	Route::post('/logincheck', 'PrivateSellerLoginController@checklogin')->name('logincheck');
	Route::get('/register', 'PrivateSellerLoginController@register')->name('PrivateSeller.register');
	Route::post('/newprivateSellerRegister', 'PrivateSellerLoginController@newprivateSellerRegister')->name('newprivateSellerRegister');
	Route::group(['middleware'=>['auth','privateSeller']], function (){
		Route::get('/dashboard', 'PrivateSellerController@index');
		Route::get('/enquiryList', 'PrivateSellerEnquiryController@enquiryList')->name('enquiryList');
	});
});


//Agent Login
Route::group(['prefix'=> 'agent/'], function (){
	Route::get('logout', function(){
   Auth::logout();
   return Redirect::to('agent/login');
});
	Route::get('/login', 'AgentLoginController@login')->name('agent.login');
	Route::post('/logincheck', 'AgentLoginController@checklogin')->name('logincheck');
	Route::get('/register', 'AgentLoginController@register')->name('agent.register');
	Route::post('/newAgentRegister', 'AgentLoginController@newagentRegister')->name('newAgentRegister');
	});
	// Route::group(['middleware'=>['auth','Agent']], function (){
Route::group(['middleware'=>['auth','Agent']], function (){
			Route::group(['prefix'=> 'agent/'], function (){
			Route::get('/dashboard', 'AgentLoginController@index');
			Route::get('/agentEnquiryList', 'AgentEnquiryController@enquiryList')->name('AgentenquiryList');
			Route::get('/enquiryDetails/{message_id}', 'AgentEnquiryController@enquiryDetail');

			Route::get('/addAuto', 'AgentAddListingsController@createAuto');
			Route::get('/addWatch', 'AgentAddListingsController@createWatch');
			Route::get('/addProperty', 'AgentAddListingsController@createProperty');

app/Http/Controllers/FaqController.php
<?php

namespace App\Http\Controllers;

use App\FaqModel;
use App\FaqCategoryModel;
use App\FaqSubCategoryModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class FaqController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Categories = FaqCategoryModel::where('status','1')->get();
        $SubCategories = FaqSubCategoryModel::where('status','1')->get();
        $FAQListing = FaqModel::get();
        return view('admin.admincommon.faq.faq.index', compact('FAQListing','Categories','SubCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $Categories = FaqCategoryModel::where('status','1')->get();
        $SubCategories = FaqSubCategoryModel::where('status','1')->get();
        return view('admin.admincommon.faq.faq.create',compact('Categories','SubCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validate($request, [
            'question'   => 'required',
            'answer'     => 'required',
            'category'   => 'required',
            'subcategory'=> 'required',
            'status'     => 'required',
        ]);

        $faq               = new FaqModel;
        $faq->question     = $request->question;
        $faq->answer       = $request->answer;
        $faq->categoryId   = $request->category;
        $faq->subcategoryId= $request->subcategory;
        $faq->status       = $request->status;
        
        $faq->save();
        return redirect('/admin/faq')->with('success_msg','FAQ added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $Categories    = FaqCategoryModel::where('status','1')->get();
        $SubCategories = FaqSubCategoryModel::where('status','1')->get();
        $editData      = FaqModel::find($id);
        return view('admin.admincommon.faq.faq.edit',compact('editData','Categories','SubCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateErr = FaqModel::find($id);

        $validate = $this->validate($request, [
            'question'   => 'required',
            'answer'     => 'required',
            'category'   => 'required',
            'subcategory'=> 'required',
            'status'     => 'required',
        ]);

        $updateErr->question      = $request->question;
        $updateErr->answer        = $request->answer;
        $updateErr->categoryId    = $request->category;
        $updateErr->subcategoryId = $request->subcategory;
        $updateErr->status        = $request->status;
        
        $updateErr->save();
        return redirect('/admin/faq')->with('success_msg','FAQ updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = FaqModel::find($id);    
        $post->delete();
        return redirect()->back()->with('success_msg','FAQ deleted successfully!');
    }
}

resources/views/admin/admincommon/faq/faq/create.blade.php
@extends('admin.common.innercommondefault')
@section('title', 'FAQ')
@section('content')
<style>
  .error { color: red; }
</style>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <div class="row">
            <div class="col-lg-8">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Add Question</h1>
                </div>
                @if($errors->any())
                  @foreach($errors->all() as $error)
                    <div class="alert alert-danger" style="color:red">
                      {{$error}}
                    </div>
                  @endforeach
                @endif
                <form class="user" id="add_question" method="POST" action="{{ route('faq.store') }}">
                  @csrf
                    <div class="form-group">
                      <label>Question</label>
                      <input id="question" class="form-control form-control-user" type="text" name="question" placeholder="Enter your question here" value="{{old('question')}}">
                    </div>
                    <div class="form-group">
                      <label>Answer</label>
                      <textarea id="answer" class="form-control form-control-user" type="text" name="answer" placeholder="Enter your answer here" maxlength="1000">@if(old('answer')){{old('answer')}}@endif</textarea>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>Category</label>
                          <select name="category" id="category" class="form-control">
                            <option value="">Select Category</option>
                            @foreach($Categories as $cat)
                            <option value="{{$cat->id}}">{{$cat->name}}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>Sub Category</label>
                          <select name="subcategory" id="subcategory" class="form-control">
                            <option value="" id="subcat_optfirst">Select Sub Category</option>
                            <!--@foreach($SubCategories as $subcat)-->
                            <!--<option value="{{$subcat->id}}">{{$subcat->name}}</option>-->
                            <!--@endforeach-->
                          </select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label>Status</label>
                          <select id ="status" name="status" class="form-control">
                            <option value="">Select Status</option>
                            <option value="1">Active</option>
                            <option value="0">Inactive</option>
                          </select>
                        </div>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">Add</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    $(document).ready(function(){
    $("#add_question").validate({
      rules: {
        question:    "required",
        answer:      "required",
        category:    "required",
        subcategory: "required",
        status:      "required"
      },
      
      messages: {
        question:    "Question can't be empty",
        answer:      "Answer can't be empty",
        category:    "Category can't be empty",
        subcategory: "Sub-Category can't be empty",
        status:      "Status can't be empty",
      },
    
      submitHandler: function(form) {
        form.submit();
      }
    });
    
    $('#category').change(function(){
      var catID = $(this).val();
      $.ajax({
        url:'/admin/faqsub-cat',
        type:'POST',
        dataType:'JSON',
        data: {categoryId: catID, _token: '{{csrf_token()}}' },
        success:function(data){
          console.log(data);
          $('.subcat_optsecond').remove();
          var option = '';
          $.each(data,function(index,value){
            option += '<option class="subcat_optsecond" value="'+value['id']+'">'+value['name']+'</option>';
          })
          $('#subcat_optfirst').after(option);
        }
      });
    });
    
  });

  </script>
@stop

resources/views/admin/admincommon/faq/faq/edit.blade.php
@extends('admin.common.innercommondefault')
@section('title', 'FAQ')
@section('content')
<style>
  .error { color: red; }
</style>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <div class="row">
            <div class="col-lg-8">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Update Question</h1>
                </div>
                @if($errors->any())
                  @foreach($errors->all() as $error)
                    <div class="alert alert-danger" style="color:red">
                      {{$error}}
                    </div>
                  @endforeach
                @endif
                <form class="user" id="add_question" method="POST" action="{{ route('faq.update',$editData->id) }}">
                  @csrf
                  @method('PUT')
                    <div class="form-group">
                      <label>Question</label>
                      <input id="question" class="form-control form-control-user" type="text" name="question" placeholder="Enter your question here" value="{{$editData->question}}">
                    </div>
                    <div class="form-group">
                      <label>Answer</label>
                      <textarea id="answer" class="form-control form-control-user" type="text" name="answer" placeholder="Enter your answer here" maxlength="1000">@if($editData->answer){{$editData->answer}}@endif</textarea>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>Category</label>
                          <select name="category" id="category" class="form-control">
                            <option value="">Select Category</option>
                            @foreach($Categories as $cat)
                            <option value="{{$cat->id}}" {{$editData->categoryId == $cat->id ? 'selected="selected"' :''}}>{{$cat->name}}</option>
                            @endforeach
                          </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                          <label>Sub Category</label>
                          <select name="subcategory" id="subcategory" class="form-control">
                            <option value="" id="subcat_optfirst">Select Sub Category</option>
                            <!--@foreach($SubCategories as $cat)-->
                            <!--<option value="{{$cat->id}}" {{$editData->subcategoryId == $cat->id ? 'selected="selected"' :''}}>{{$cat->name}}</option>-->
                            <!--@endforeach-->
                          </select>
                        </div>
                    </div>
                  </div>
                  <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Status</label>
                      <select id ="status" name="status" class="form-control">
                        <option value="">Select Status</option>
                        <option value="1" {{$editData->status == '1' ? 'selected="selected"' :''}}>Active</option>
                        <option value="0" {{$editData->status == '0' ? 'selected="selected"' :''}}>InActive</option>
                      </select>
                    </div>
                    </div>
                  </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">Update</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    $(document).ready(function(){
    $("#add_question").validate({
      rules: {
        question: "required",
        answer: "required",
        categories: "required",
        status: "required"
      },
      
      messages: {
        question: "Question can't be empty",
        answer: "Answer can't be empty",
        categories: "Category can't be empty",
        status: "Status can't be empty",
      },
    
      submitHandler: function(form) {
        form.submit();
      }
    }); 
  
  $('#category').change(function(){
      var catID = $(this).val();
      $.ajax({
        url:'/admin/faqsub-cat',
        type:'POST',
        dataType:'JSON',
        data: {categoryId: catID, _token: '{{csrf_token()}}' },
        success:function(data){
          console.log(data);
          $('.subcat_optsecond').remove();
          var option = '';
          var subcategorycheck = "<?php echo $editData->subcategoryId;?>";
          $.each(data,function(index,value){
            if(subcategorycheck == value['id']){
              var select = 'selected';
            }else{
              var select = '';
            }
            option += '<option class="subcat_optsecond" value="'+value['id']+'" '+select+' >'+value['name']+'</option>';
          })
          $('#subcat_optfirst').after(option);
        }
      });
    });
  });

  $(document).ready(function(){
    var catID = $('#category').val();
      $.ajax({
        url:'/admin/faqsub-cat',
        type:'POST',
        dataType:'JSON',
        data: {categoryId: catID, _token: '{{csrf_token()}}' },
        success:function(data){
          console.log(data);
          $('.subcat_optsecond').remove();
          var option = '';
          var subcategorycheck = "<?php echo $editData->subcategoryId;?>";
          $.each(data,function(index,value){
            if(subcategorycheck == value['id']){
              var select = 'selected';
            }else{
              var select = '';
            }
            option += '<option class="subcat_optsecond" value="'+value['id']+'" '+select+' >'+value['name']+'</option>';
          })
          $('#subcat_optfirst').after(option);
        }
      });
    }); 

  </script>
@stop

resources/views/admin/admincommon/faq/faq/index.blade.php
@extends('admin.common.innercommondefault')
@section('title', 'FAQ Page')
@section('content')
  <div id="wrapper">
    <div id="content-wrapper" class="d-flex flex-column">
      @if(isset($Categories[0]->id) && isset($SubCategories[0]->id))
      <div id="content">
        <div class="container-fluid">
          <h1 class="h3 mb-2 text-gray-800">FAQ</h1>
         	@can('superAdmin-create')
         		<a href="{{route('faq.create')}}" class="btn btn-primary btn-icon-split">
            		<span class="text">Add New Question</span>
          		</a>
         	@endcan
          @if(Session::has('success_msg'))
          	<div class="alert " id="writeMsg" style="background-color: #4e73df;margin-top: 20px;color: white;">{{ Session::get('success_msg') }}</div>
          @endif
          <div id="main"></div>
          	<div class="card shadow mb-4" style="margin-top: 10px;">
            	<div class="card-body" >
             		<div class="table-responsive">
               		<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               			<thead>
                 			<tr>
                 				<th>S.No.</th>
				                <th>Question</th>
                        <th>Answer</th>
				                <th>Category</th>
                        <th>Sub Category</th>
                        <th>Status</th>
					  				    @can('superAdmin-create')
                      	 <th>Action</th>
                      	@endcan
                    	</tr>
                  	</thead>
		                <tbody>
                      <?php $i=1;?>
                    	@foreach($FAQListing as $faq)
                      	<tr>
                          <td>{{$i}}</td>
                    			<td>{{$faq->question}}</td>
                    			<td>{{$faq->answer}}</td>
                          <td>
                            @foreach($Categories as $cat)
                              @if($faq->categoryId == $cat->id)
                                {{$cat->name}}
                              @endif
                            @endforeach
                          </td>
                          <td>
                            @foreach($SubCategories as $cat1)
                              @if($faq->subcategoryId == $cat1->id)
                                {{$cat1->name}}
                              @endif
                            @endforeach
                          </td>
                          <td>
                   					@if($faq->status =='1') Active @else InActive @endif  
                        	</td>
                          @can('superAdmin-create')
                          <td>
                            {!! Form::open(['method'=>'DELETE', 'url' =>route('faq.destroy', $faq->id),'style' => 'display:inline']) !!}
                            {!! Form::button('<i class="fas fa-trash-alt"></i>', array('type' => 'submit','class' => 'btn','title' => 'Delete Post','onclick'=>'return confirm("Confirm delete?")')) !!}
                            {!! Form::close() !!}
                              <a  href="{{route('faq.edit',$faq->id)}}">
                                <i class="fas fa-edit"></i>
                              </a> &nbsp; &nbsp;
                          </td>
                        @endcan
                      	</tr>
                        <?php $i++;?>
                    	@endforeach
                  	</tbody>
                	</table>
              	</div>
            	</div>
          	</div>
          </div>
      </div>
      @else
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
              <div class="card-body p-0 alert-danger text-center">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="p-5">
                      There is <b style="color: red;">No FAQ Category / Sub Category found or Active</b>!!
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    @endif
  </div>
</div>
@stop